Repository accentor/api, pull requests merged in 2020-04, with the labels that each got.

#26 Find genre based on sort_name in rescan
  app/models/rescan_runner.rb
Labels: enhancement

#29 Use new serializing for track merge action
  app/controllers/tracks_controller.rb
  test/controllers/tracks_controller_test.rb
  test/models/track_test.rb
Labels: bug

#30 Configure new cops
  .rubocop.yml
Labels: chore

#28 Allow merging of genres
  app/controllers/genres_controller.rb
  app/models/genre.rb
  app/policies/genre_policy.rb
  config/routes.rb
  test/controllers/genres_controller_test.rb
  test/models/genre_test.rb
Labels: enhancement

#31 Change track merge behaviour to avoid throwing away audio files
  app/models/track.rb
  test/models/track_test.rb
Labels: enhancement

#32 Run annotate, which annotates the serializers
  app/serializers/album_artist_serializer.rb
  app/serializers/album_label_serializer.rb
  app/serializers/album_serializer.rb
  app/serializers/artist_serializer.rb
  app/serializers/auth_token_serializer.rb
  app/serializers/codec_conversion_serializer.rb
  app/serializers/codec_serializer.rb
  app/serializers/cover_filename_serializer.rb
  app/serializers/genre_serializer.rb
  app/serializers/image_type_serializer.rb
  app/serializers/label_serializer.rb
  app/serializers/location_serializer.rb
  app/serializers/rescan_runner_serializer.rb
  app/serializers/track_artist_serializer.rb
  app/serializers/track_serializer.rb
  app/serializers/user_serializer.rb
  config/routes.rb
Labels: chore

#35 Remove some unused lines that can never be covered by tests
  app/jobs/application_job.rb
  app/policies/application_policy.rb
Labels: chore

#34 Allow labels to be merged
  app/controllers/labels_controller.rb
  app/models/label.rb
  app/policies/label_policy.rb
  config/routes.rb
  test/controllers/labels_controller_test.rb
  test/models/label_test.rb
Labels: enhancement

#36 Report branch coverage
  test/test_helper.rb
Labels: chore

#38 Add policies and serializers to their own group
  test/test_helper.rb
Labels: chore

#43 Allow a blank string as AlbumArtist separator
  app/models/album.rb
  test/models/album_test.rb
Labels: bug
