Repository accentor/api, pull requests merged in 2020-12, with the labels that each got.

#129 Add test for transcode cache clean job
  config/environments/test.rb
  test/jobs/transcode_cache_clean_job_test.rb
Labels: chore

#126 Test audio action of tracks controller
  app/controllers/tracks_controller.rb
  test/controllers/tracks_controller_test.rb
Labels: chore

#149 Add basic pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#158 Don't crash on invalid date in tag
  app/models/rescan_runner.rb
  test/files/success-invalid-date/dd-mm-yy.flac
  test/files/success-invalid-date/mm-dd-yy.flac
  test/files/success-invalid-date/some-te-xt.flac
  test/files/success-invalid-date/sometext.flac
  test/models/rescan_runner_test.rb
Labels: bug

#159 Don't include full backtrace of error in prod
  app/models/rescan_runner.rb
Labels: enhancement

#162 Make storage definitions public for image permalinks
  config/storage.yml
Labels: enhancement

#164 Switch ruby setup in CI to action from ruby org
  .github/workflows/ci.yml
Labels: chore, github_actions

#163 Upgrade ruby to 3.0.0
  .ruby-version
  Gemfile
  Gemfile.lock
Labels: chore
