Repository accentor/api, pull requests merged in 2021-07, with the labels that each got.

#224 Update LICENSE year
  LICENSE
Labels: chore

#114 Add plays model
  app/controllers/plays_controller.rb
  app/models/play.rb
  app/models/track.rb
  app/models/user.rb
  app/policies/play_policy.rb
  app/serializers/play_serializer.rb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20210104190247_create_plays.rb
  db/schema.rb
  test/controllers/plays_controller_test.rb
  test/factories/plays.rb
  test/models/play_test.rb
  test/models/track_test.rb
Labels: enhancement

#225 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#160 Add basic readme
  README.md
Labels: documentation

#227 Add note about rights for screenshots to bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: chore

#230 Add GitHub action to automatically create a release when a tag is pushed
  .github/release-drafter.yml
  .github/workflows/release.yml
Labels: chore

#231 Run CI actions on pull request and pushes to tags or main branch
  .github/workflows/ci.yml
Labels: chore

#235 Always add composer from track's metadata
  app/models/rescan_runner.rb
Labels: enhancement
