Repository accentor/api, pull requests merged in 2023-10, with the labels that each got.

#487 Add download action for tracks
  app/controllers/tracks_controller.rb
  app/policies/track_policy.rb
  config/routes.rb
  test/controllers/tracks_controller_test.rb
Labels: enhancement

#480 Remove delayed job
  Gemfile
  Gemfile.lock
  bin/delayed_job
  config/initializers/delayed_job.rb
  db/migrate/20230910071837_drop_delayed_jobs_table.rb
  db/schema.rb
  gemset.nix
Labels: chore

#494 Add rubocop-factory_bot
  .rubocop.yml
  Gemfile
  Gemfile.lock
  gemset.nix
  test/controllers/albums_controller_test.rb
  test/controllers/artists_controller_test.rb
  test/controllers/auth_tokens_controller_test.rb
  test/controllers/cover_filenames_controller_test.rb
  test/controllers/genres_controller_test.rb
  test/controllers/labels_controller_test.rb
  test/controllers/locations_controller_test.rb
  test/controllers/tracks_controller_test.rb
  test/factories/albums.rb
  test/factories/artists.rb
  test/factories/auth_tokens.rb
  test/factories/codec_conversions.rb
  test/factories/playlist_items.rb
  test/factories/tracks.rb
  test/models/rescan_runner_test.rb
Labels: chore

#491 Update to rails 7.1
  Gemfile
  Gemfile.lock
  bin/setup
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  gemset.nix
  test/controllers/rescans_controller_test.rb
Labels: dependencies, ruby
