Repository accentor/api, pull requests merged in 2024-10, with the labels that each got.

#647 Remove obsolete `check_file_attributes` method
  app/models/audio_file.rb
  test/models/audio_file_test.rb
Labels: chore

#648 Remove migrations that are more than 2 years old
  db/migrate/20190326075117_create_users.rb
  db/migrate/20190326075520_create_auth_tokens.rb
  db/migrate/20190326122335_create_codecs.rb
  db/migrate/20190327072133_create_locations.rb
  db/migrate/20190327075150_create_audio_files.rb
  db/migrate/20190327081039_create_image_types.rb
  db/migrate/20190327103442_create_cover_filenames.rb
  db/migrate/20190327133415_create_codec_conversions.rb
  db/migrate/20190327160521_create_active_storage_tables.active_storage.rb
  db/migrate/20190327160723_create_images.rb
  db/migrate/20190328162017_create_albums.rb
  db/migrate/20190329093706_create_artists.rb
  db/migrate/20190329105717_create_genres.rb
  db/migrate/20190329135413_create_labels.rb
  db/migrate/20190329140742_create_album_labels.rb
  db/migrate/20190330082129_create_tracks.rb
  db/migrate/20190330145446_create_track_genre_join_table.rb
  db/migrate/20190331093927_create_track_artists.rb
  db/migrate/20190331170233_create_delayed_jobs.rb
  db/migrate/20190331174813_create_rescan_runners.rb
  db/migrate/20190420094159_add_review_comment_to_track.rb
  db/migrate/20190421121809_add_review_comment_to_album.rb
  db/migrate/20190421121933_add_review_comment_to_artist.rb
  db/migrate/20190423191851_create_album_artists.rb
  db/migrate/20190427120544_add_order_to_track_artists.rb
  db/migrate/20190503135843_add_edition_information_to_album.rb
  db/migrate/20190724090720_create_content_lengths.rb
  db/migrate/20200201191707_add_normalized_columns.rb
  db/migrate/20200318125903_remove_album_label_cat_nr_null.rb
  db/migrate/20200321105358_add_finished_at_to_rescan_runner.rb
  db/migrate/20200705102418_add_sample_rate_and_bit_depth_to_audio_file.rb
  db/migrate/20200720073351_create_transcoded_items.rb
  db/migrate/20200720092916_add_cron_to_delayed_jobs.rb
  db/migrate/20201212115621_add_service_name_to_active_storage_blobs.active_storage.rb
  db/migrate/20201212115622_create_active_storage_variant_records.active_storage.rb
  db/migrate/20210104190247_create_plays.rb
  db/migrate/20210905090539_add_location_to_rescan_runner.rb
  db/migrate/20211127114919_add_hidden_to_track_artists.rb
  db/migrate/20220219105635_remove_not_null_on_active_storage_blobs_checksum.active_storage.rb
  db/migrate/20220327115559_create_playlists.rb
  db/migrate/20220327120150_create_playlist_items.rb
  db/migrate/20220430121719_change_null_album_release.rb
Labels: chore

#644 Precache actual files instead of storing lengths
  README.md
  app/controllers/tracks_controller.rb
  app/jobs/calculate_content_length_job.rb
  app/jobs/convert_transcode_job.rb
  app/jobs/create_transcoded_item_job.rb
  app/jobs/queue_transcoded_items_for_codec_conversion_job.rb
  app/jobs/recalculate_content_lengths_job.rb
  app/jobs/transcode_cache_clean_job.rb
  app/models/audio_file.rb
  app/models/codec_conversion.rb
  app/models/content_length.rb
  app/models/transcoded_item.rb
  config/application.rb
  config/brakeman.ignore
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/good_job.rb
  db/migrate/20241004203216_delete_content_lengths.rb
  db/migrate/20241004230124_remove_last_used_from_transcoded_items.rb
  db/schema.rb
  lib/tasks/ffmpeg.rake
  test/controllers/tracks_controller_test.rb
  test/factories/transcoded_items.rb
  test/jobs/calculate_content_length_job_test.rb
  test/jobs/convert_transcode_job_test.rb
  test/jobs/create_transcoded_item_job_test.rb
  test/jobs/queue_transcoded_items_for_codec_conversion_job_test.rb
  test/jobs/transcode_cache_clean_job_test.rb
  test/models/audio_file_test.rb
  test/models/codec_conversion_test.rb
  test/models/transcoded_item_test.rb
Labels: enhancement

#650 Make sure we wait for ffmpeg to finish when transcoding
  app/models/audio_file.rb
Labels: bug

#656 Make `audio_file#convert` raise an exception on failure
  app/models/audio_file.rb
  test/models/audio_file_test.rb
Labels: chore

#659 Transcode to a temporary file which is only moved when finished
  app/jobs/create_transcoded_item_job.rb
  app/models/audio_file.rb
  test/controllers/tracks_controller_test.rb
  test/jobs/create_transcoded_item_job_test.rb
  test/models/audio_file_test.rb
  test/test_helper.rb
Labels: chore
